### ISSUE TITLE
Add more capability to manage terraform runs

### ISSUE THREAD

**Issue by sevaine** [octoenergy/terraform-enterprise-client#18]
This library and CLI would be far more useful if it were possible to query workspaces for information about their runs, for example:

- List the latest N runs for a workspace
- List the latest N runs for a workspace, filtered by run status, or title
- Cancel or discard a specific run ID
- Cancel or discard a group of runs matching a filter (run_status, title, time period)

**Comment by richardcooper** [comment]
I'm closing this issue because we're archiving this project.

Thank you for your interest in this project.
