### ISSUE TITLE
Add a "Contributing" section in the README

### ISSUE THREAD

**Issue by richardcooper** [octoenergy/terraform-enterprise-client#2]
It would be useful to have a "Contributing" section in the README which explains how people can install the repo locally and run the tests etc.

**Comment by davzucky** [comment]
@richardcooper Thank you for the project. I had the same idea and  I would like to contribute to it. For the moment I'm more interesting about allowing to apply the change from a workspace which we can only do from the UI. 
Could you let me know what is the current state of contributing?

**Comment by richardcooper** [comment]
@davzucky Hi. I hope this project can be of some help to you. Issues and PRs welcome!

Could you maybe open another issue explaining your "apply the change from a workspace which we can only do from the UI." issue in a bit more detail.

**Comment by richardcooper** [comment]
Added `contributing` and `development` sections to the README in #8
